language: python

python:
    - "2.7"

install: pip install -r requirements.txt

script: nosetests -w pdl_scraper --cover-package=pdl_scraper --with-coverage --cover-inclusive --cover-erase

after_success: coveralls
